# Site
name: 'Aaradhika'
description: 'मनुष्य के आत्म विकास के लिए जीवन में दैवीय गुणों को ग्रहण करना एकमात्र श्रेष्ठ और सरल उपाय है । इसी सत्य को जानकर चालीस साल पहले मेरी रूचि विभिन्न पुराणों व धार्मिक पुस्तकों को पढ़ने में हुई । उसी ज्ञान को आप सब लोगों को अवगत कराने के पावन उद्देश्य से मैंने यह ब्लॉग लिखने का निर्णय लिया है । आशा करती हूँ कि आप मेरे इस प्रयास से अवश्य ही कुछ नयी जानकारी हासिल करेंगे ।'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'ashutosh.ag.87@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    sal:
      name:           Archana Agarwal
      site:           https://hi.quora.com/profile/Archana-Agarwal-142
      avatar:         /assets/images/avatar1.jpg
      bio:            "Editor in Chief @ Aaradhika.com"
      email:          archana.agwl@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Ashutosh Agarwal
      site:           https://twitter.com/aasus
      avatar:         /assets/images/avatar2.jpg
      bio:            "CEO, Aaradhika.com"
      email:          ashutosh.ag.87@gmail.com
      twitter:        https://twitter.com/aasus

    archanaagwl:
      name:           Archana Agarwal
      site:           https://hi.quora.com/profile/Archana-Agarwal-142
      avatar:         /assets/images/avatar1.jpg
      bio:            "Editor in Chief @ Aaradhika.com"
      email:          archana.agwl@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      email:          archana.agwl@gmail.com
      display_name:   Archana Agarwal
      first_name:     Archana
      last_name:      Agarwal

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
